enabled: true
readonly: true
language: en
caseSensitive: false

useGitignore: false # ensures better compatibility when used in multiple projects

enabledFileTypes:
- cpp
- c
- markdown
- cmake
- json
- yaml

files: /**
ignorePaths:
- doc/CMakeLists.txt
- .clangd
- .cspell.yaml
- build/**

words:
 - embeutils
 - embetile
 - embetech